In [1]:
import pandas as pd
import numpy as np

s = pd.Series(np.random.randint(0, 1000, 1000))
s

0       38
1      355
2      501
3      369
4      965
      ...
995    111
996    712
997    603
998    465
999    693
Length: 1000, dtype: int32

In [2]:
%%timeit -n 10

s = pd.Series(np.random.randint(0, 1000, 1000))
for label, value in s.items():
    s.loc[label] = value+2

33.5 ms ± 3.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [3]:
%%timeit -n 10

s = pd.Series(np.random.randint(0, 1000, 1000))

s+=2

215 μs ± 28.3 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [4]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
}, 
index=["Row1", "Row2", "Row3"]
)

print(df)
print(df.dtypes)
print(df.index)
print(df.columns)

      A  B  C
Row1  1  4  7
Row2  2  5  8
Row3  3  6  9
A    int64
B    int64
C    int64
dtype: object
Index(['Row1', 'Row2', 'Row3'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')

In [5]:
print("iloc first row:")
print(df.iloc[0])

print("iloc second row, column B:")
print(df.iloc[1, 1])

print("loc row 3:")
print(df.loc["Row3"])

print("loc column A for all rows:")
print(df.loc[:,"A"])

iloc first row:
A    1
B    4
C    7
Name: Row1, dtype: int64
iloc second row, column B:
5
loc row 3:
A    3
B    6
C    9
Name: Row3, dtype: int64
loc column A for all rows:
Row1    1
Row2    2
Row3    3
Name: A, dtype: int64

In [6]:
mask = (df["A"] > 1) & (df["B"]>4)
print(mask)

filtered = df[mask]
print(filtered)

Row1    False
Row2     True
Row3     True
dtype: bool
      A  B  C
Row2  2  5  8
Row3  3  6  9

In [7]:
df["D"] = df["A"] + df["B"]
df["E"] = df["A"] * df["B"]

print(df)

      A  B  C  D   E
Row1  1  4  7  5   4
Row2  2  5  8  7  10
Row3  3  6  9  9  18

In [8]:
df = pd.DataFrame({
    "Category": ["A", "B", "A", "B", "A"],
    "Value": [5, 10, 15, 20, 25]
})

df

  Category  Value
0        A      5
1        B     10
2        A     15
3        B     20
4        A     25

In [9]:
grouped = df.groupby("Category")
result = grouped.agg({"Value": ["mean", "sum"]})
result

         Value
          mean sum
Category
A         15.0  45
B         15.0  30

In [10]:
import pandas as pd

df = pd.read_csv("Admission_Predict.csv", index_col=0)
stripped_cols = [x.lower().strip() for x in df.columns]
df.columns = stripped_cols
df.head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [11]:
admit_mask = df['chance of admit'] > 0.7
admit_mask.head()

Serial No.
1     True
2     True
3     True
4     True
5    False
Name: chance of admit, dtype: bool

In [12]:
df.where(admit_mask).head()

# or just use
# df = df[admit_mask]

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.where(admit_mask).dropna().head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
6,330.0,115.0,5.0,4.5,3.0,9.34,1.0,0.90

In [14]:
# Way better method to include where() and dropna()

df[df['chance of admit'] > 0.7].head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
6,330,115,5,4.5,3.0,9.34,1,0.90

In [15]:
df['gre score'].head()

Serial No.
1    337
2    324
3    316
4    322
5    314
Name: gre score, dtype: int64

In [16]:
df[["gre score", "toefl score"]].head()

            gre score  toefl score
Serial No.
1                 337          118
2                 324          107
3                 316          104
4                 322          110
5                 314          103

In [17]:
# multiple boolean mask criteria using | and &

mask = (df['chance of admit'] > 0.7) & (df['chance of admit'] < 0.9)
df[mask]

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
7,321,109,3,3.0,4.0,8.20,1,0.75
12,327,111,4,4.0,4.5,9.00,1,0.84
...,...,...,...,...,...,...,...,...
393,326,112,4,4.0,3.5,9.12,1,0.84
394,317,104,2,3.0,3.0,8.76,0,0.77
395,329,111,4,4.5,4.0,9.23,1,0.89
396,324,110,3,3.5,3.5,9.04,1,0.82
397,325,107,3,3.0,3.5,9.11,1,0.84

In [18]:
# also works with gt() - greater than and lt() - lower than

df['chance of admit'].gt(0.7) & df['chance of admit'].lt(0.9)

Serial No.
1      False
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398    False
399    False
400    False
Name: chance of admit, Length: 400, dtype: bool

In [19]:
# or by chaining them together

df['chance of admit'].gt(0.7).lt(0.9)

Serial No.
1      False
2      False
3      False
4      False
5       True
       ...
396    False
397    False
398    False
399     True
400    False
Name: chance of admit, Length: 400, dtype: bool

In [20]:
# from the beginning
import pandas as pd

df = pd.read_csv("Admission_Predict.csv", index_col=0)
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [22]:
df['Serial Number'] = df.index

df = df.set_index('Chance of Admit ')
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Serial Number
Chance of Admit,,,,,,,,
0.92,337,118,4,4.5,4.5,9.65,1,1
0.76,324,107,4,4.0,4.5,8.87,1,2
0.72,316,104,3,3.0,3.5,8.00,1,3
0.80,322,110,3,3.5,2.5,8.67,1,4
0.65,314,103,2,2.0,3.0,8.21,0,5

In [23]:
df = df.reset_index()
df.head()

,Chance of Admit,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Serial Number
0,0.92,337,118,4,4.5,4.5,9.65,1,1
1,0.76,324,107,4,4.0,4.5,8.87,1,2
2,0.72,316,104,3,3.0,3.5,8.00,1,3
3,0.80,322,110,3,3.5,2.5,8.67,1,4
4,0.65,314,103,2,2.0,3.0,8.21,0,5